### ISSUE TITLE
Add writing support

### ISSUE THREAD

**Issue by njh** [njh/node-red-contrib-owfs#10]
Test using this:
http://www.sheepwalkelectronics.co.uk/product_info.php?cPath=23&products_id=59

**Comment by erichabg** [comment]
I would like to promote this feature request.  In my 1-wire network there are not only sensors but also actors like DS2405. To be able to switch them would be great.

**Comment by njh** [comment]
Request noted. Will try and find some time to get my DS2413 tested/working.

**Comment by njh** [comment]
Tried adding write support, but there is a bug in version 0.2.3 of the owfs node module that means writing doesn't work.

A fix has been contributed:
https://github.com/benediktarnold/owfs/pull/14

But it has not been released.

Additionally, because it is written in coffee script, installing directly from git doesn't work - nothing is re-compiling the JavaScript.

**Comment by njh** [comment]
I am now the maintainer of the owfs node package. I have released version 0.2.4 that fixes support for owfs.

Writing support added in f522abafe59e045781c1ea4a96055b2daa13a4b4.

Going to do some more testing, then do a release to npm.

**Comment by njh** [comment]
I have been running this for quite a while without any problems.

Released version [1.2.0](https://github.com/njh/node-red-contrib-owfs/tree/1.2.0) today.
