### ISSUE TITLE
Add onewire Hub management

### ISSUE THREAD

**Issue by CondormanFr** [njh/node-red-contrib-owfs#11]
I own 2 [Hobby Boards 4 Channel Hub](http://owfs.org/index.php?page=4-channel-hub) 

With OWFS web server or OpenHAB, i can access all my devices on my branches (aux and main).
It gives me path like : `1F.F26505000000/aux/28.D7BF94020000/temperature`
But the node-red owfs contrib does not allow me to access the devices under aux and main.

Is it possible to add this support in the node-red owfs plugin ?
Thanks

**Comment by njh** [comment]
Hi,

I had hoped that the last release would have added support for active 1-wire hubs - it does a recursive search of the bus.

Sadly I don't own a Hobby Boards 4 Channel Hub (and I guess I never will now), but it should be possible to simulate with a fake server.

nick.

**Comment by CondormanFr** [comment]
Then wait.
I was using a 5 month old release. I will build my new docker image with the 3 month old recursive search and test again.
Romain

**Comment by CondormanFr** [comment]
Great. In fact, your recursive search works. I can read my sensor under branches
Thanks and sorry for the unnecessary issue

**Comment by njh** [comment]
It is actually really useful to know that someone has tested this and that it works :)
