### ISSUE TITLE
Unable to catch owfs errors in a catch node

### ISSUE THREAD

**Issue by colinl** [njh/node-red-contrib-owfs#6]
I have an owfs node configured to fetch a value from a remote owserver.  If that server is unable to reach the sensor then in node-red I see in the console and in the debug window an error of the form
[error] [owfs:Name] Communication Error. Received -1
and it seems that the owfs node does not send a message.  To attempt to cope with this I added a Catch node on the tab, but it does not seem to catch the owfs error.
Running on Pi (Jessie)
owfs node version 0.2.0
Node-RED version: v0.13.3
Node.js  version: v0.10.29
Linux 4.1.19-v7+ arm LE

**Comment by colinl** [comment]
I believe this may be due to not passing the message to node.error as in http://nodered.org/docs/writing-functions#handling-errors
I will have a go at sorting it and submit a PR if I succeed

**Comment by njh** [comment]
This has been on my todo list for quite a long time (#5).

If you manage to submit a PR, that would be fantastic :smiley:

**Comment by colinl** [comment]
I saw the other issue, but I thought it was something different.  The error failing to reach the sensor does not cause node- red to die, it just logs an error on the console and does nothing else.
It will likely be a few days before I can get round to doing anything, but it is causing me problems so I have an incentive.

**Comment by njh** [comment]
Fixed in #7
